name: Migrating Java Application
 
on:
  push:
    branches:
      - main
    paths:
      - 'Spring-Java11-mvc/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    # Step 3: Rewrite code
    - name: Rewrite code
      run: |
        sudo apt install maven -y
        mvn -version
        cd Spring-Java11-mvc
        mvn install -DskipTests
        mvn rewrite:run

    # Step 4: Configure Git identity
    - name: Configure Git identity
      run: |
        git config --global user.email "mahorjitendra@gmail.com"
        git config --global user.name "jeet041"

    # Step 5: Check if folder exists and move files
    - name: Check if folder exists and move files
      run: |
        if [ ! -d "migrated-folder" ]; then
          mkdir migrated-folder
          mv Spring-Java11-mvc/* migrated-folder/  # Moves files from specific-folder to new-folder
          cd ./migrated-folder
          git add .
          git commit -m "Move files to new folder"
          git push origin master  # Pushes changes to the master branch
        else
          echo " migrated-folder already exists, skipping move operation"
        fi
